### PR TITLE
Fix configuration cache compatibility

### LINKED ISSUE #10: Configuration cache problems found in this build
Hello, thank you for this plugin - I am now trying to integrate it to our multiplatform module.

Unfortunately I am receiving build erorr:

```
Configuration cache problems found in this build.

2 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:my-module:generateTranslateFile` of type `com.hyperether.localization.GenerateTranslationsTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.14.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

See the complete report at file {path to file}
> Invocation of 'Task.project' by task ':my-module:generateTranslateFile' at execution time is unsupported.
```

When I disabled configuration cache in `gradle.properties` (`org.gradle.configuration-cache=false`) it starts working fine, but using cache is beneficial, so I would prefer to being able to use it in the future. Is there a way to fix it?

### PR DESCRIPTION
**Pull request by Nouran-11**
Fixes #10

### CODE REVIEW

**Review by NikolaHadzicNs — APPROVED** [review]

File: compose-multiplatform-localize-gradle/compose-multiplatform-localize-plugin/src/main/java/com/hyperether/localization/LocalizationPlugin.kt [hunk 1]
```diff
@@ -25,12 +25,15 @@ abstract class GenerateTranslationsTask : DefaultTask() {
     @get:Input
     abstract val resourcesDir: Property<String>
 
+    @get:Input
```
Comment (abstratt) [inline compose-multiplatform-localize-gradle/compose-multiplatform-localize-plugin/src/main/java/com/hyperether/localization/LocalizationPlugin.kt:28]: 👎 

This should be `@Internal` instead
